name: neetpg_mcq
description: NEET-PG MCQ personal practice app with imported offline question bank.
publish_to: "none"
version: 3.0.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/mcqs.json
